import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:tuoora/config/app_routes.dart';
import 'package:tuoora/core/constants/app_colors.dart';
import 'package:tuoora/core/constants/app_text_styles.dart';
import 'package:tuoora/core/theme/app_spacing.dart';
import 'package:tuoora/presentation/student/controllers/fees_controller.dart';
import 'package:tuoora/presentation/student/widgets/student_app_bar.dart';

class StudentReceiptsListScreen extends StatelessWidget {
  const StudentReceiptsListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.studentBg,
      body: SafeArea(
        child: Column(
          children: [
            const StudentAppBar(
              title: 'Receipts',
              showDefaultActions: false,
            ),
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      '3 receipts available - all generated by Saraswati Coaching',
                      style: AppTextStyles.lexend(
                        fontSize: 12,
                        color: AppColors.textSecondary,
                      ),
                    ),
                    const SizedBox(height: 16),
                    _buildReceiptCard('April 2026', 'INV-2026-04', 'UPI', 'PhonePe', '₹4,500'),
                    const SizedBox(height: 12),
                    _buildReceiptCard('March 2026', 'INV-2026-03', 'Cash', '', '₹4,500'),
                    const SizedBox(height: 12),
                    _buildReceiptCard('Jan 2026', 'INV-2026-01', 'UPI', 'GPay', '₹4,500'),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildReceiptCard(
    String month,
    String invoiceId,
    String method,
    String app,
    String amount,
  ) {
    return GestureDetector(
      onTap: () {
        final feesController = Get.find<FeesController>();
        final statement = feesController.statements.firstWhere(
          (s) => s.id == invoiceId,
          // Fallback to the first available paid statement if not exactly matched
          orElse: () => feesController.statements.firstWhere((s) => s.status.name == 'paid', orElse: () => feesController.statements.first),
        );
        feesController.openReceipt(statement);
      },
      child: Container(
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: AppColors.white,
          borderRadius: BorderRadius.circular(8),
          border: Border.all(color: AppColors.borderGrey.withOpacity(0.5)),
        ),
        child: Row(
          children: [
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: const Color(0xFFDCFCE7),
                borderRadius: BorderRadius.circular(8),
              ),
              child: const Icon(
                Icons.download_rounded,
                color: Color(0xFF14532D),
                size: 20,
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    month,
                    style: AppTextStyles.manrope(
                      fontSize: 14,
                      fontWeight: FontWeight.w800,
                      color: AppColors.textPrimary,
                    ),
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      Text(
                        invoiceId,
                        style: AppTextStyles.lexend(
                          fontSize: 11,
                          color: AppColors.textSecondary,
                        ),
                      ),
                      Text(
                        '  ·  $method',
                        style: AppTextStyles.lexend(
                          fontSize: 11,
                          color: AppColors.textSecondary,
                        ),
                      ),
                      if (app.isNotEmpty)
                        Text(
                          '  ·  $app',
                          style: AppTextStyles.lexend(
                            fontSize: 11,
                            color: AppColors.textSecondary,
                          ),
                        ),
                    ],
                  ),
                ],
              ),
            ),
            Text(
              amount,
              style: AppTextStyles.manrope(
                fontSize: 14,
                fontWeight: FontWeight.w800,
                color: AppColors.textPrimary,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
